runner:
  bandit:
    cmd:  'bandit -r ./ -f custom --msg-template "{relpath}:{line}:{col}:{test_id}:{severity}:{msg}" | tee "$PWD"/scan_results/banditResults.txt' 
    errorformat: # (optional if you use `format`)
      - "%f:%l:%c:%m" 
    name: bandit # (optional. you can overwrite <tool-name> defined by runner key)
    level: info # (optional. same as -level flag. [info,warning,error])
  hadolint:
    cmd: './bin/hadolint -c .github/.hadolint.yaml Dockerfile.* -f json | jq -f ".github/.rdjson.jq" -c | tee "$PWD"/scan_results/hadolintResults.txt'
    format: rdjson
    level: error # (optional. same as -level flag. [info,warning,error])
  shellcheck:
    cmd: shellcheck **/*.sh -f gcc | tee "$PWD"/scan_results/shellcheckResults.txt
    errorformat: 
      - "%f:%l:%c:%m" 
  pycodestyle:
    cmd: pycodestyle **/*.py | tee "$PWD"/scan_results/pep8Results.txt
    format: pep8
  # golangci-lint:
  #   cmd: ./bin/golangci-lint run --config .github/.golangci.yml --out-format=line-number **/*.go
  #   format: golangci-lint
