# Copyright Â© 2024 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: automated-self-checkout
description: A Helm chart for the Automated Self-Checkout System
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - dlstreamer
  - object-detection
sources:
home:
